from django.urls import path
from econ import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.index, name="index"),
    path("admin_dashboard/", views.admin_dashboard, name="admin_dashboard"),
    path("login/", views.login, name="login"),
    path("login_process", views.login_process, name="login_process"),
    path("logout_process", views.logout_process, name="logout_process"),
    path("profile/", views.profile, name="profile"),
    path("bookmark/toggle/", views.toggle_bookmark, name="toggle_bookmark"),
    path("study/progress/toggle/", views.toggle_study_progress, name="toggle_study_progress"),
    path("study/note/save/", views.save_item_note, name="save_item_note"),
    path("study/quiz/submit/", views.submit_item_quiz, name="submit_item_quiz"),
    path("registration/", views.registration, name="registration"),
    path("registration_process", views.registration_process, name="registration_process"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("forum/", views.forum, name="forum"),
    path("forum/new/", views.forum_create_thread, name="forum_create_thread"),
    path("forum/<int:thread_id>/", views.forum_thread, name="forum_thread"),
    path("forum/<int:thread_id>/reply/", views.forum_reply, name="forum_reply"),
    path("forum/<int:thread_id>/like/", views.forum_toggle_thread_like, name="forum_toggle_thread_like"),
    path("forum/<int:thread_id>/delete/", views.forum_delete_thread, name="forum_delete_thread"),
    path("forum/reply/<int:reply_id>/like/", views.forum_toggle_reply_like, name="forum_toggle_reply_like"),
    path("forum/reply/<int:reply_id>/delete/", views.forum_delete_reply, name="forum_delete_reply"),
    path("blog/", views.blog, name="blog"),
    path("blog/<slug:slug>/", views.blog_detail, name="blog_detail"),
    path("blog/<slug:slug>/edit/", views.edit_blog, name="edit_blog"),
    path("blog/<slug:slug>/delete/", views.delete_blog, name="delete_blog"),
    path("vlog/", views.vlog, name="vlog"),
    path("vlog/<int:vlog_id>/", views.vlog_detail, name="vlog_detail"),
    path("vlog/<int:vlog_id>/edit/", views.edit_vlog, name="edit_vlog"),
    path("vlog/<int:vlog_id>/delete/", views.delete_vlog, name="delete_vlog"),
    path("gallery/", views.gallery, name="gallery"),
    path("gallery/<int:media_id>/edit/", views.edit_gallery_entry, name="edit_gallery_entry"),
    path("gallery/<int:media_id>/delete/", views.delete_gallery_entry, name="delete_gallery_entry"),
    path("journal/", views.journal, name="journal"),
    path("journal/<int:journal_id>/", views.journal_detail, name="journal_detail"),
    path("journal/<int:journal_id>/edit/", views.edit_journal, name="edit_journal"),
    path("journal/<int:journal_id>/delete/", views.delete_journal, name="delete_journal"),
    path('download_sql_dump', views.download_sql_dump, name='download_sql_dump'),
    path('upload_sql_process', views.upload_sql_process, name='upload_sql_process'),
    path('upload_sql', views.upload_sql, name='upload_sql'),
    path("admin/audit-logs/", views.audit_logs, name="audit_logs"),
    path("admin/add-blog/", views.add_blog, name="add_blog"),
    path("admin/add-journal/", views.add_journal, name="add_journal"),
    path("admin/add-image/", views.add_image, name="add_image"),
    path("admin/add-video/", views.add_video, name="add_video"),
    path("admin/add-media/", views.add_media, name="add_media"),
    path("admin/add-vlog/", views.add_vlog, name="add_vlog"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
