# Generated by Django 6.0.4 on 2026-05-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0009_journalentry_citation_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_section',
            name='post',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='citation_info',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.DeleteModel(
            name='post',
        ),
        migrations.DeleteModel(
            name='post_section',
        ),
    ]
