# Generated by Django 6.0.5 on 2026-05-19 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0010_remove_post_section_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField()),
                ('icon', models.CharField(default='fa-train', max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'topic',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='econ.topic'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='econ.topic'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='journal_entries', to='econ.topic'),
        ),
        migrations.AddField(
            model_name='mediagalleryentry',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='media_entries', to='econ.topic'),
        ),
    ]
