# Generated by Django 6.0.5 on 2026-05-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0012_seed_topics_and_group_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
