# Generated by Django 6.0.5 on 2026-05-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0014_restore_dashboard_topic_cards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vlog',
            options={'ordering': ['order', 'vlogID']},
        ),
        migrations.AddField(
            model_name='vlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vlog',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vlog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vlog',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vlog',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vlog',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='vlog_entries', to='econ.topic'),
        ),
        migrations.AddField(
            model_name='vlog',
            name='video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
