# Generated by Codex on 2026-05-19

import re

from django.db import migrations, models


CHANNEL_NAMES = {
    "1idZRXTlo48": "EIT Urban Mobility",
    "NF6xMiH_Lt4": "Atkins",
    "yGTiJ8gXc60": "EconomyTalk",
    "U3x86Hcr1R8": "EconomyTalk",
    "S0bAAqitw8A": "Hitachi",
}

VIDEO_ID_PATTERN = re.compile(
    r"(?:https?://)?(?:www\.)?(?:youtube\.com/watch\?v=|youtube\.com/embed/|youtube\.com/shorts/|youtu\.be/)([A-Za-z0-9_-]{11})"
)


def seed_channel_names(apps, schema_editor):
    Vlog = apps.get_model("econ", "vlog")

    for video in Vlog.objects.all():
        match = VIDEO_ID_PATTERN.search(video.video_url or "")
        if not match:
            continue

        channel_name = CHANNEL_NAMES.get(match.group(1))
        if channel_name:
            video.channel_name = channel_name
            video.save(update_fields=["channel_name"])


def unseed_channel_names(apps, schema_editor):
    Vlog = apps.get_model("econ", "vlog")
    Vlog.objects.update(channel_name="")


class Migration(migrations.Migration):

    dependencies = [
        ("econ", "0016_seed_vlog_topic_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="vlog",
            name="channel_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.RunPython(seed_channel_names, unseed_channel_names),
    ]
