# Generated by Codex on 2026-05-19

from django.db import migrations


def rename_gallery_entries(apps, schema_editor):
    MediaGalleryEntry = apps.get_model("econ", "MediaGalleryEntry")
    MediaGalleryEntry.objects.filter(title="Shinkansen, Japan").update(
        title="Modern City Trains"
    )
    MediaGalleryEntry.objects.filter(title="MRT, Philippines").update(
        title="Crowded Rush Hour Train"
    )


def unrename_gallery_entries(apps, schema_editor):
    MediaGalleryEntry = apps.get_model("econ", "MediaGalleryEntry")
    MediaGalleryEntry.objects.filter(title="Modern City Trains").update(
        title="Shinkansen, Japan"
    )
    MediaGalleryEntry.objects.filter(title="Crowded Rush Hour Train").update(
        title="MRT, Philippines"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("econ", "0017_vlog_channel_name"),
    ]

    operations = [
        migrations.RunPython(rename_gallery_entries, unrename_gallery_entries),
    ]
