# Generated by Django 6.0.5 on 2026-05-19 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0018_seed_topic_quizzes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('blog', 'Blog'), ('journal', 'Journal'), ('video', 'Video')], max_length=20)),
                ('item_id', models.PositiveIntegerField()),
                ('question', models.CharField(max_length=300)),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(max_length=200)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('explanation', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'item_quiz_question',
                'ordering': ['item_type', 'item_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItemQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=20)),
                ('item_id', models.PositiveIntegerField()),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('total', models.PositiveSmallIntegerField(default=0)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'item_quiz_attempt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('blog', 'Blog'), ('journal', 'Journal'), ('video', 'Video')], max_length=20)),
                ('item_id', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'item_note',
                'constraints': [models.UniqueConstraint(fields=('user', 'item_type', 'item_id'), name='unique_user_item_note')],
            },
        ),
    ]
