# Generated by Django 6.0.5 on 2026-05-19 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0020_seed_item_quizzes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemquizquestion',
            options={'ordering': ['item_type', 'item_id', 'round_number', 'order', 'id']},
        ),
        migrations.AddField(
            model_name='itemquizattempt',
            name='round_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='itemquizquestion',
            name='round_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ItemQuizProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=20)),
                ('item_id', models.PositiveIntegerField()),
                ('perfect_rounds', models.PositiveSmallIntegerField(default=0)),
                ('mastered', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_quiz_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'item_quiz_progress',
                'constraints': [models.UniqueConstraint(fields=('user', 'item_type', 'item_id'), name='unique_user_item_quiz_progress')],
            },
        ),
    ]
