# Generated by Django 5.1.15 on 2026-05-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0020_restore_asean_rail_blog_sources'),
        ('econ', '0023_mix_quiz_option_positions'),
    ]

    operations = [
    ]
