# Generated by Django 5.1.15 on 2026-05-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0024_merge_20260519_1846'),
        ('econ', '0025_merge_0023_mix_quiz_option_positions_0024_refresh_journal_and_vlog_text'),
    ]

    operations = [
    ]
