# Generated by Django 6.0.5 on 2026-05-19 12:49

from django.db import migrations, models


def ensure_itemnote_user_index(apps, schema_editor):
    ItemNote = apps.get_model("econ", "ItemNote")
    table_name = ItemNote._meta.db_table
    index_name = "item_note_user_idx"
    user_column = ItemNote._meta.get_field("user").column

    with schema_editor.connection.cursor() as cursor:
        constraints = schema_editor.connection.introspection.get_constraints(cursor, table_name)

    for constraint in constraints.values():
        if constraint.get("index") and constraint.get("columns") == [user_column]:
            return

    schema_editor.add_index(
        ItemNote,
        models.Index(fields=["user"], name=index_name),
    )


def drop_itemnote_user_index(apps, schema_editor):
    ItemNote = apps.get_model("econ", "ItemNote")
    table_name = ItemNote._meta.db_table
    index_name = "item_note_user_idx"

    with schema_editor.connection.cursor() as cursor:
        constraints = schema_editor.connection.introspection.get_constraints(cursor, table_name)

    if index_name not in constraints:
        return

    schema_editor.remove_index(
        ItemNote,
        models.Index(fields=["user"], name=index_name),
    )


def drop_unique_user_item_note(apps, schema_editor):
    ItemNote = apps.get_model("econ", "ItemNote")
    table_name = ItemNote._meta.db_table
    constraint_name = "unique_user_item_note"

    with schema_editor.connection.cursor() as cursor:
        constraints = schema_editor.connection.introspection.get_constraints(cursor, table_name)

    if constraint_name not in constraints:
        return

    if schema_editor.connection.vendor == "mysql":
        quoted_table = schema_editor.quote_name(table_name)
        quoted_constraint = schema_editor.quote_name(constraint_name)
        schema_editor.execute(f"ALTER TABLE {quoted_table} DROP INDEX {quoted_constraint}")
        return

    constraint = next(
        constraint
        for constraint in ItemNote._meta.constraints
        if constraint.name == constraint_name
    )
    schema_editor.remove_constraint(ItemNote, constraint)


def restore_unique_user_item_note(apps, schema_editor):
    ItemNote = apps.get_model("econ", "ItemNote")
    table_name = ItemNote._meta.db_table
    constraint_name = "unique_user_item_note"

    with schema_editor.connection.cursor() as cursor:
        constraints = schema_editor.connection.introspection.get_constraints(cursor, table_name)

    if constraint_name in constraints:
        return

    constraint = models.UniqueConstraint(
        fields=["user", "item_type", "item_id"],
        name=constraint_name,
    )
    schema_editor.add_constraint(ItemNote, constraint)


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0026_merge_20260519_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemnote',
            options={'ordering': ['-updated_at']},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    ensure_itemnote_user_index,
                    reverse_code=drop_itemnote_user_index,
                ),
                migrations.RunPython(
                    drop_unique_user_item_note,
                    reverse_code=restore_unique_user_item_note,
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='itemnote',
                    name='unique_user_item_note',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='itemnote',
            name='note',
            field=models.CharField(max_length=50),
        ),
    ]
