# Generated by Django 6.0.5 on 2026-05-19 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0028_forumthread_forumreply'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumThreadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='forum_threads/%Y/%m/%d/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='econ.forumthread')),
            ],
            options={
                'db_table': 'forum_thread_image',
                'ordering': ['order', 'id'],
            },
        ),
    ]
