# Generated by Django 6.0.5 on 2026-05-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0029_forumthreadimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='additional_topics',
            field=models.ManyToManyField(blank=True, related_name='forum_additional_threads', to='econ.topic'),
        ),
    ]
