# Generated by Codex on 2026-05-20

from django.db import migrations


def update_mobility_economy_icon(apps, schema_editor):
    Topic = apps.get_model("econ", "Topic")
    Topic.objects.filter(key="mobility-economy").update(icon="fa-chart-line")


def restore_mobility_economy_icon(apps, schema_editor):
    Topic = apps.get_model("econ", "Topic")
    Topic.objects.filter(key="mobility-economy").update(icon="fa-chart-simple")


class Migration(migrations.Migration):

    dependencies = [
        ("econ", "0031_forumreplyimage"),
    ]

    operations = [
        migrations.RunPython(
            update_mobility_economy_icon,
            restore_mobility_economy_icon,
        ),
    ]
