# Generated by Django 6.0.5 on 2026-05-20 06:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0032_update_mobility_economy_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumreply',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_forum_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_forum_threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
