# Generated by Django 5.1.15 on 2026-05-20 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0032_seed_blog_3_and_blog_5'),
        ('econ', '0033_forumreply_likes_forumthread_likes'),
    ]

    operations = [
    ]
